Error handling
surveylyzer/product pull request #31
Opened 2020-05-12 20:14 UTC by dubelbog

- add page reload for results page to avoid small display of results
- add 'surveylyzer' logo for every page as home page button
- replace alerts within DropArea through IonAlert
- add Error Handling for raw data url
- add Error Handling and alerts to improve usability for:
   - Invalid or Empty 'Result ID'
   - Another File Extension for uploaded Files as PDF
   - Errors within PDF Analyzer / Server

2020-05-13 17:41 UTC, empedokles3 requested changes
Funktioniert soweit.
Hinweis: wenn man als erste Auswertung eine korrekte laufen lässt. und die zweite ist dann fehlerhaft. wird die Erste im Hintergrund unter /result angezeigt.
Wenn man dann eine neue korrekte Auswertung machen möchte. dann wird die erste wieder angezeigt....

2020-05-13 19:28 UTC, dubelbog commented
@empedokles3 
Danke fürs Testen.
Ich konnte es auch reproduzieren. Man muss dann die Seite neu laden und dann wird man auf die richtige Auswertung resp. Berechnung umgeleitet.
Ich schaue in dem Fall ob ich an der richtigen Stelle im Code einen page reload einbauen kann, damit es dann automatisch passiert und der Fehler nicht auftritt.

2020-05-13 19:54 UTC, dubelbog commented
Der Bug ist nun gefixt.

2020-05-14 06:25 UTC, empedokles3 approved these changes
Passt.

2020-05-14 06:25 UTC, merged